# Generated by Django 2.0.7 on 2018-07-28 15:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_auto_20180728_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
