# Generated by Django 2.0.7 on 2018-08-01 07:18

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0004_auto_20180731_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pagenos',
            new_name='totalpages',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='books', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(verbose_name='ISBN'),
        ),
    ]
