# Generated by Django 2.0.7 on 2018-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0006_auto_20180801_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(max_length=200, upload_to='images/'),
        ),
    ]
